### ISSUE TITLE
Implement design for replying with image

### ISSUE THREAD

**Issue by saulmc** [ephemeraHQ/converse-app#557]
When I reply with an image, there is no visual link back to the message I was replying to.

Designs provided below.

**Comment by alexrisch** [comment]
@saulmc I think this is resolved, is that correct?
If not is this expected to get design feedback?

**Comment by saulmc** [comment]
I think this is still an issue. When I reply with an image, there is no visual link back to the message I was replying to. There are a couple ways could go with this, so I consider it blocked on design. /cc @covrter

**Comment by alexrisch** [comment]
Ah yes sorry I mis understood, my fault

**Comment by covrter** [comment]
Here we go y'all! 

- Essentially we place the "quoted message" bubble up above the media.
- I like introducing the lil Reply icon next to the username of the replied-to user — this would apply to all "quoted message" bubbles. Feels subtle enough to not distract but also like it adds a lil clarity. But IDK, might be overthinking it, we can leave it out as well and/or add it later.

https://www.figma.com/design/p6mt4tEDltI4mypD3TIgUk/Converse-App?node-id=2488-17483&t=GvsjjPMhSQAfiNhP-1

![CleanShot 2024-10-04 at 14 46 52@2x](https://github.com/user-attachments/assets/85e8b15d-b0f9-4829-bed8-8c08328ca8b7)

**Comment by covrter** [comment]
Check it @saulmc and hit me with feedback and/or drop it into our queue

**Comment by saulmc** [comment]
lgtm! @covrter should that little arrow be added to all quoted
messages, or just the ones where the reply is an image?

**Comment by covrter** [comment]
Great question — I imagine it being included in all Replies as a quick visual cue. Kind of like this.

![Image](https://github.com/user-attachments/assets/307153f8-0ddc-4fb3-94ab-16fa039f3199)
